### ISSUE TITLE
warning about wrong nest structure

### ISSUE THREAD

**Issue by yiminghe** [react-component/menu#17] opened 2015-11-06 08:49 UTC
``` js
const A = React.createClass({
  render() {
    return <MenuItem />
  }
});

const B = React.createClass({
  render() {
    return <Menu><A /><A /></Menu>;
  }
});
```

**Comment by benjycui** [comment] 2017-04-19 02:04
What does this mean?

**Comment by benjycui** [comment] 2017-04-19 02:05
We can wrap Menu.Item?

**Comment by picodoth** [comment] 2018-06-09 07:45
I think the problem is not there anymore, closing

**Closed by picodoth** 2018-06-09 07:45 UTC
